# Generated by Django 3.1.4 on 2022-11-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0002_auto_20221124_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='user',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
